version: '3'

services:
  mongo:
    image: mongo:5.0.9-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    volumes:
      - mongodb:/data/db
    user: root

  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    restart: always
    depends_on:
      - mongo

  store-server:
    build:
      context: .
    image: store-server
    ports:
      - 50051:50051
    environment:
      PORT: 50051
      MONGO_URI: mongodb://admin:admin@mongo:27017

volumes:
  mongodb: